# Site settings
title: Kevin Liu
tagline: Stay hungry, stay foolish
email: xckevin927@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mobile Developer <p> 专注移动开发，擅长Android，略懂iOS、H5、JavaWeb等技术. <p> 目前base在中国·杭州
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://xckevin.github.io/"   # the base hostname & protocol for your site
logourl: /assets/images/logo.png # Site logo
author: "Kevin Liu"
author_thumbnail: "/assets/images/avatar.jpg" # Author avatar
# Theme customization - please change from the defaults!
theme:
  # Color for sidebar bar, links, etc
  highlight_color: "#90A959" #205081" # "#272935"
  # Social media links, leave blank to ignore
  social: 
    github: xckevin
    #twitter: gayanvirajith
    #facebook: gayanvirajith
    gplus: +xckevin927
    # dribble: gayanvirajith
    # pinterest: gayanvirajith

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: false

  # Disqus comments manager - shortname
  # disqus_shortname: gaya-webcreate

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: 
  google_webmaster_key: 

# Build settings
markdown: kramdown

# Permalinks
permalink:        pretty

# Pagination config
gems: [jekyll-paginate]
paginate: 8

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: assets/css/_sass
  style: :compressed
